# Generated by Django 5.0.6 on 2024-06-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='datas',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
